version: '3.4'

services:
  week2bookdocker:
    container_name: week2bookdocker
    restart: always
    build:
      context: .
    ports:
      - 5000:5000
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
